[package]
name = "cipher"
version = "0.1.0"
authors = ["Felix Viernickel <f.viernickel@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
generic-array = "0.14.4"
typenum = "1.12.0"
